---

tasks:
  - name: Install JetBrains DataSpell Editor
    when: development.editors | enabled('dataspell')
    winget:
      package: JetBrains.DataSpell
      state: "${{ development.editors | enabled('dataspell') | ternary('present', 'absent') }}"
      source: winget