---

tasks:
  - name: Install Golang
    tags: 
      - languages
      - languages.golang
    winget:
      package: "GoLang.Go"
      state: ${{ languages.golang | enabled() | ternary('latest', 'absent') }}

  - name: Install Golangci-lint
    tags: 
      - languages
      - languages.golang
    eget:
      package: "golangci/golangci-lint"
      state: ${{ languages.golang | enabled() | ternary('latest', 'absent') }}

  - name: Install GoReleaser
    tags: 
      - languages
      - languages.golang
    winget:
      package: "GoReleaser.GoReleaser"
      state: ${{ languages.golang | enabled() | ternary('latest', 'absent') }}