---

tasks:
  - name: Install Golang
    tags: 
      - languages
      - languages.golang
    winget:
      package: "GoLang.Go"
      state: ${{ languages.golang | enabled() | ternary('present', 'absent') }}

  - name: Install Golangci-lint
    tags: 
      - languages
      - languages.golang
    eget:
      package: "golangci/golangci-lint"
      state: ${{ languages.golang | enabled() | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join(item.bin) }}
    with:
      bin: "${{ (facts.os_family == 'windows') | ternary('golangci-lint.exe', 'golangci-lint') }}"

  - name: Cleanup GoReleaser
    tags: 
      - languages
      - languages.golang
    winget:
      package: "goreleaser.goreleaser"
      state: absent

  - name: Install GoReleaser
    tags: 
      - languages
      - languages.golang
    eget:
      package: "goreleaser/goreleaser"
      state: ${{ languages.golang | enabled() | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join(item.bin) }}
    with:
      bin: "${{ (facts.os_family == 'windows') | ternary('goreleaser.exe', 'goreleaser') }}"
    when:
      - languages.golang | enabled()