---

tasks:
  - name: Install JetBrains CLion Editor
    when: development.editors | enabled('clion')
    winget:
      package: JetBrains.CLion
      state: "${{ development.editors | enabled('clion') | ternary('present', 'absent') }}"
      source: winget