---
tasks:

  - name: Install Microsoft Edge
    tags:
      - productivity.browsers
      - productivity.browsers.edge
    when: productivity.browsers.edge is defined
    winget:
      package: Microsoft.Edge
      state: ${{ productivity.browsers | enabled('edge') | ternary('present', 'absent') }}

  - name: Install Microsoft Edge Beta
    tags:
      - productivity.browsers
      - productivity.browsers.edge_beta
    when: productivity.browsers.edge_beta is defined
    winget:
      package: Microsoft.Edge.Beta
      state: ${{ productivity.browsers | enabled('edge_beta') | ternary('present', 'absent') }}

  - name: Install Microsoft Edge Canary
    tags:
      - productivity.browsers
      - productivity.browsers.edge_canary
    when: productivity.browsers.edge_canary is defined
    winget:
      package: Microsoft.Edge.Canary
      state: ${{ productivity.browsers | enabled('edge_canary') | ternary('present', 'absent') }}

  - name: Install Microsoft Edge Dev
    tags:
      - productivity.browsers
      - productivity.browsers.edge_dev
    when: productivity.browsers.edge_dev is defined
    winget:
      package: Microsoft.Edge.Dev
      state: ${{ productivity.browsers | enabled('edge_dev') | ternary('present', 'absent') }}