---

tasks:
  - name: Install Zettlr Editor
    tags:
      - development
      - development.editors
      - development.editors.zettlr
    when: development.editors.zettlr is defined
    winget:
      package: Zettlr.Zettlr
      state: "${{ development.editors | enabled('zettlr') | ternary('present', 'absent') }}"
      source: winget