---
vars:
  productivity:
    browsers: false
      # chrome: true
      # chrome_beta: false
      # chrome_canary: false
      # chrome_dev: false
      # firefox: true
      # edge: true
      # edge_beta: false
      # edge_canary: false
      # edge_dev: false
      # opera: false
      # opera_beta: false
      # opera_dev: false
      # operagx: false
    cloud_storage: false
      # box: true
      # google_drive: true
      # onedrive: true
      # dropbox: true

tasks:
  - name: Include Browsers Role
    tags:
      - productivity
      - productivity.browsers
    when: productivity | enabled('browsers')
    include:
      name: roles/productivity/browsers

  - name: Include Cloud Storage Role
    tags:
      - productivity
      - productivity.cloud_storage
    when: productivity | enabled('cloud_storage')
    include:
      name: roles/productivity/cloud-storage

  - name: Include Communication Role
    tags:
      - productivity
      - productivity.communication
    when: productivity | enabled('communication')
    include:
      name: roles/productivity/communication
