---
vars:
  local:
    bin_path: ~/.local/bin
  monitoring: false
  cli: false
  tweaks: false
  terminal: false
  security: false
  development:
    editors: false
      # vscode: true
  languages: false
    # rust: false
    # python: false
    # nodejs: false
    # golang: false
    # java: false
      # jre: false
      # jdk: EclipseAdoptium.Temurin.21.JDK
    # dotnet: false
    # ruby: false
      # install:
      #   override: '/verysilent /tasks="assocfiles,modpath" /DIR="d:\ruby" /currentuser'
  shell:
    pwsh:
      profile: '~/.config/powershell/Microsoft.PowerShell_profile.ps1'
      aliases: '~/.config/powershell/custom/aliases/dev.ps1'
      dev: '~/Development'
      ws: '~/Development'
      omp:
        profile: '~/.config/powershell/default.omp.json'

  defaults:
    languages:
      java:
        jre: false
        jdk: Microsoft.OpenJDK.25
      nodejs: OpenJS.NodeJS
      dotnet:
        runtime: false # Microsoft.DotNet.Runtime.10
        sdk: Microsoft.DotNet.SDK.10
      python: 'Python.Python.3.13'
      ruby: RubyInstallerTeam.Ruby.4.0
    shell:
      pwsh:
        profile: '~/.config/powershell/Microsoft.PowerShell_profile.ps1'
        aliases: '~/.config/powershell/custom/aliases/dev.ps1'
        dev: '~/Development'
        ws: '~/Development'
        omp:
          profile: '~/.config/powershell/default.omp.json'
# intentionally left empty
# tasks can be defined in hosts/<hostname>.yml or in variables/<username>.yml 
# to allow specific tasks to be run for a specific host or user.
# this can be tasks that are meant to be applied to all.
tasks:

  - name: Local Binaries Path Fact
    fact:
      name: local_bin_path
      value: ${{ local.bin_path | default('~/.local/bin') }}

  - name: Verify Local Binaries Path Fact
    assert:
      that:
        - facts.local_bin_path is defined
        - facts.local_bin_path | length > 0
        - facts.local_bin_path | exists
      fail_msg: "Local bin path fact is not defined or empty. Please define 'vars.local.bin_path' in your inventory or host vars."
      success_msg: "Local bin path fact is defined and valid. Path: ${{ facts.local_bin_path }}"
  - name: Include Windows Subsystem for Linux (WSL)
    include:
      name: roles/wsl
