---

version: '3'
vars:
  MACOS_USER: ryan
  MACOS_IP: '192.168.2.25'
  WSL_USER: ryan
# includes:
#   local: .local.taskfile.yml
    # taskfile: .local.taskfile.yml
    # optional: true

tasks:
  build:
    desc: Build the project
    cmds:
      - echo "Building the project..."
      - mkdir -p bin
      - go mod tidy
      - golangci-lint run ./...
      - goreleaser build --snapshot --clean
      - go vet ./cmd/ironstate
      - gofmt -l .
      - go test ./...

  push:
    # deps:
    #   - build
    desc: Push the built binary to the remote server
    cmds: 
      - echo "Starting the push process..."
      - echo "Push to local bin directory"
      - cp ./dist/ironstate_windows_amd64_v1/ironstate.exe ~/.local/bin/ironstate.exe
      - echo "Pushing the built binary to the remote server..."
      - scp ./dist/ironstate_darwin_amd64_v1/ironstate {{.MACOS_USER}}@{{.MACOS_IP}}:/Users/{{.MACOS_USER}}/.local/bin/
      - echo "Pushing the built binary to the WSL distributions..."
      - echo "... Ubuntu ..."
      - wsl -d Ubuntu cp /home/{{.WSL_USER}}/Development/oss/ironstate/dist/ironstate_linux_amd64_v1/ironstate /home/{{.WSL_USER}}/.local/bin/
      - echo "... Debian ..."
      - wsl -d Debian cp /home/{{.WSL_USER}}/Development/oss/ironstate/dist/ironstate_linux_amd64_v1/ironstate /home/{{.WSL_USER}}/.local/bin/
      - echo "... KaliLinux ..."
      - wsl -d KaliLinux cp /home/{{.WSL_USER}}/Development/oss/ironstate/dist/ironstate_linux_amd64_v1/ironstate /home/{{.WSL_USER}}/.local/bin/
      - echo "... ArchLinu x..."
      - wsl -d ArchLinux cp /home/{{.WSL_USER}}/Development/oss/ironstate/dist/ironstate_linux_amd64_v1/ironstate /home/{{.WSL_USER}}/.local/bin/
      - echo "... Alpine ..."
      - wsl -d Alpine cp /home/{{.WSL_USER}}/Development/oss/ironstate/dist/ironstate_linux_amd64_v1/ironstate /home/{{.WSL_USER}}/.local/bin/
      - echo "... DONE ..."