defaults:
  user: rconr
  port: 22
hosts:
  snoke:   { address: 192.168.2.103, platform: linux, user: ryan }
  kresh:   { address: 192.168.2.10, platform: windows }
  krayt:   { address: 192.168.2.3, platform: windows }
groups:
  linux: [snoke]
  windows: [krayt, kresh]