defaults:
  user: rconr
  port: 22
hosts:
  snoke:
    address: 192.168.2.103
    platform: linux
    user: ryan
  kresh:
    address: 192.168.2.10
    platform: windows
  krayt:
    address: 192.168.2.3
    platform: windows
  anaxes:
    address: 192.168.2.1
    platform: linux
    user: admin
    port: 8338
    become: false
    verify_agent: false
  atrius:
    address: 192.168.2.25
    platform: darwin
    user: ryan
groups:
  linux: 
    - snoke
    - anaxes
  windows:
    - krayt
    - kresh
  darwin:
    - atrius