---

tasks:

  - name: Set up Git
    tags:
      - development
      - development.git
    include:
      name: roles/development/git

  - name: Set up Docker
    tags:
      - development
      - development.docker
    include:
      name: roles/development/docker

  - name: Set up GitHub SSH hosts
    tags:
      - development
      - development.github
    include:
      name: roles/development/github

  - name: Set up Development Folders
    tags:
      - development
    include:
      name: roles/development/folder

  - name: Set up Development Tools
    tags:
      - development
      - development.tools
    include:
      name: roles/development/tools

  - name: Set up Development Agents
    tags:
      - development
      - development.agents
    include:
      name: roles/development/agents

  - name: Set up Development Editors
    tags:
      - development
      - development.editors
    when: development.editors is mapping or (development.editors)
    include:
      name: roles/development/editors

  - name: Set up development alias
    blockinfile:
      create: true
      dest: ${{ shell.pwsh.aliases | default('~/.config/powershell/Microsoft.PowerShell_profile.ps1') | dirname | join('dev.ps1') }}
      block: |
        Remove-Item Alias:dev -ErrorAction SilentlyContinue
        Remove-Item Alias:ws -ErrorAction SilentlyContinue
        function dev {
          Set-Location '${{ shell.pwsh.dev | default('~/Development') }}'
        }
        function ws {
          Set-Location '${{ shell.pwsh.ws | default('~/Development') }}'
        }
