---

vars:
  development:
    root: d:/Development
    oss: d:/Development/projects/github
    work: d:/Development/work/imanage
  monitoring: false
  cli: false
  languages: 
    rust: true
    python: true
    nodejs: true
    golang: true
    java: false
      # jre: false
      # jdk: EclipseAdoptium.Temurin.21.JDK
    dotnet: true
    ruby: false
      # install:
      #   override: '/verysilent /tasks="assocfiles,modpath" /DIR="d:\ruby" /currentuser'
  shell:
    pwsh:
      profile: '~/.config/powershell/profile.ps1'
      aliases: '~/.config/powershell/custom/aliases/default.ps1'
      dev: '~/Development'
      ws: '~/Development'

tasks:

  - include:
      name: hosts/camalot
