---

tasks:

  - name: Install JetBrains PyCharm Editor
    when: development.editors | enabled('pycharm')
    winget:
      package: JetBrains.PyCharm.Community
      state: "${{ development.editors | enabled('pycharm') | ternary('present', 'absent') }}"
      source: winget