---

tasks:

  # not entirely sure how i want to handle this yet.
  # it will need to look at the `facts.wsl_installed` and then create a function shim
  # in powershell custom scripts to wrap the `wsl nano $@` command.

  - name: Install Nano Shim
    tags:
      - nano
    include:
      name: tasks/wsl-shim
      with:
        command: nano
