---

tasks:

  - name: Install Nano Shim
    tags:
      - development
      - development.editors
      - development.editors.nano
    include:
      name: tasks/wsl-shim
      state: ${{ development.editors | enabled('nano') | ternary('present', 'absent') }}
      with:
        command: nano
