---

tasks:
  - name: Docker Desktop
    tags:
      - development
      - development.docker
    winget:
      package: Docker.DockerDesktop
      state: ${{ development.docker | enabled() | ternary('present', 'absent') }}