---

tasks:
  - name: Install doggo CLI
    tags: 
      - dns
      - network
      - cli
    eget:
      package: mr-karan/doggo
      state: ${{ package.state }}
      args:
        - --to=~/.local/bin/doggo.exe
        - --upgrade-only

  - name: Create symlink for doggo
    tags:
      - dog
      - cli
    symlinks:
      src: ~/.local/bin/doggo.exe
      dest: ~/.local/bin/dog.exe
      state: ${{ package.state }}
