---

tasks:
  - name: Install JetBrains ReSharper
    when: development.editors | enabled('resharper')
    winget:
      package: JetBrains.ReSharper
      state: "${{ development.editors | enabled('resharper') | ternary('present', 'absent') }}"
      source: winget