---

tasks:

  - name: Install Opera
    tags:
      - productivity.browsers
      - productivity.browsers.opera
    when: productivity.browsers.opera is defined
    winget:
      package: Opera.Opera
      state: ${{ productivity.browsers | enabled('opera') | ternary('present', 'absent') }}

  - name: Install Opera Beta
    tags:
      - productivity.browsers
      - productivity.browsers.opera_beta
    when: productivity.browsers.opera_beta is defined
    winget:
      package: Opera.Opera.Beta
      state: ${{ productivity.browsers | enabled('opera_beta') | ternary('present', 'absent') }}

  - name: Install Opera Developer
    tags:
      - productivity.browsers
      - productivity.browsers.opera_dev
    when: productivity.browsers.opera_dev is defined
    winget:
      package: Opera.Opera.Dev
      state: ${{ productivity.browsers | enabled('opera_dev') | ternary('present', 'absent') }}

  - name: Install Opera GX
    tags:
      - productivity.browsers
      - productivity.browsers.operagx
      - productivity.browsers.opera_gx # support both tags
    when: productivity.browsers.operagx is defined
    winget:
      package: Opera.OperaGX
      state: ${{ productivity.browsers | enabled('operagx') | ternary('present', 'absent') }}