---

tasks:
  - name: Install JetBrains RustOver Editor
    when: development.editors | enabled('rustover')
    winget:
      package: JetBrains.RustOver
      state: "${{ development.editors | enabled('rustover') | ternary('present', 'absent') }}"
      source: winget