---

tasks:
  - name: Install JetBrains DataGrip Editor
    when: development.editors | enabled('datagrip')
    winget:
      package: JetBrains.DataGrip
      state: "${{ development.editors | enabled('datagrip') | ternary('present', 'absent') }}"
      source: winget