---
tasks:
  - name: Include Microsoft Edge Installation
    include:
      name: roles/productivity/browsers/edge

  - name: Include Mozilla Firefox Installation
    include:
      name: roles/productivity/browsers/firefox

  - name: Include Opera Installation
    include:
      name: roles/productivity/browsers/opera

  - name: Include Google Chrome Installation
    include:
      name: roles/productivity/browsers/chrome
