---

tasks:

  - name: Set up Git
    tags:
      - git
      - development
    include:
      name: roles/development/git
      state: present

  - name: Set up Development Folders
    tags:
      - development
    include:
      name: roles/development/folder
      state: present

  - name: Set up Development Tools
    tags:
      - development
    include:
      name: roles/development/tools
      state: present

  - name: Set up Development Agents
    tags:
      - development
    include:
      name: roles/development/agents
      state: present

  - name: Set up development alias
    blockinfile:
      create: true
      dest: ${{ shell.pwsh.aliases | default('~/.config/powershell/Microsoft.PowerShell_profile.ps1') | dirname | join('dev.ps1') }}
      block: |
        Remove-Item Alias:dev -ErrorAction SilentlyContinue
        Remove-Item Alias:ws -ErrorAction SilentlyContinue
        function dev {
          Set-Location '${{ shell.pwsh.dev | default('~/Development') }}'
        }
        function ws {
          Set-Location '${{ shell.pwsh.ws | default('~/Development') }}'
        }
