---

tasks:

  - name: Sysinternals Suite
    when: system.tools | enabled('sysinternals')
    include:
      name: roles/system/tools/sysinternals
      state: ${{ system.tools | enabled('sysinternals') | ternary('latest', 'absent') }}
    tags:
      - system
      - system.tools
      - system.tools.sysinternals