// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/handler.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandlerPlugin_ListHandlers_FullMethodName = "/ironstate.plugin.v1.HandlerPlugin/ListHandlers"
	HandlerPlugin_Test_FullMethodName         = "/ironstate.plugin.v1.HandlerPlugin/Test"
	HandlerPlugin_Describe_FullMethodName     = "/ironstate.plugin.v1.HandlerPlugin/Describe"
	HandlerPlugin_Install_FullMethodName      = "/ironstate.plugin.v1.HandlerPlugin/Install"
	HandlerPlugin_Uninstall_FullMethodName    = "/ironstate.plugin.v1.HandlerPlugin/Uninstall"
	HandlerPlugin_FactName_FullMethodName     = "/ironstate.plugin.v1.HandlerPlugin/FactName"
	HandlerPlugin_ScanRole_FullMethodName     = "/ironstate.plugin.v1.HandlerPlugin/ScanRole"
	HandlerPlugin_Scan_FullMethodName         = "/ironstate.plugin.v1.HandlerPlugin/Scan"
)

// HandlerPluginClient is the client API for HandlerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandlerPluginClient interface {
	ListHandlers(ctx context.Context, in *ListHandlersRequest, opts ...grpc.CallOption) (*ListHandlersResponse, error)
	Test(ctx context.Context, in *HandlerRequest, opts ...grpc.CallOption) (*TestResponse, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Install(ctx context.Context, in *HandlerRequest, opts ...grpc.CallOption) (*ExecResult, error)
	Uninstall(ctx context.Context, in *HandlerRequest, opts ...grpc.CallOption) (*ExecResult, error)
	FactName(ctx context.Context, in *FactNameRequest, opts ...grpc.CallOption) (*FactNameResponse, error)
	ScanRole(ctx context.Context, in *ScanRoleRequest, opts ...grpc.CallOption) (*ScanRoleResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type handlerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerPluginClient(cc grpc.ClientConnInterface) HandlerPluginClient {
	return &handlerPluginClient{cc}
}

func (c *handlerPluginClient) ListHandlers(ctx context.Context, in *ListHandlersRequest, opts ...grpc.CallOption) (*ListHandlersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHandlersResponse)
	err := c.cc.Invoke(ctx, HandlerPlugin_ListHandlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) Test(ctx context.Context, in *HandlerRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, HandlerPlugin_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, HandlerPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) Install(ctx context.Context, in *HandlerRequest, opts ...grpc.CallOption) (*ExecResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResult)
	err := c.cc.Invoke(ctx, HandlerPlugin_Install_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) Uninstall(ctx context.Context, in *HandlerRequest, opts ...grpc.CallOption) (*ExecResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResult)
	err := c.cc.Invoke(ctx, HandlerPlugin_Uninstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) FactName(ctx context.Context, in *FactNameRequest, opts ...grpc.CallOption) (*FactNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactNameResponse)
	err := c.cc.Invoke(ctx, HandlerPlugin_FactName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) ScanRole(ctx context.Context, in *ScanRoleRequest, opts ...grpc.CallOption) (*ScanRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanRoleResponse)
	err := c.cc.Invoke(ctx, HandlerPlugin_ScanRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerPluginClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, HandlerPlugin_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandlerPluginServer is the server API for HandlerPlugin service.
// All implementations must embed UnimplementedHandlerPluginServer
// for forward compatibility.
type HandlerPluginServer interface {
	ListHandlers(context.Context, *ListHandlersRequest) (*ListHandlersResponse, error)
	Test(context.Context, *HandlerRequest) (*TestResponse, error)
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Install(context.Context, *HandlerRequest) (*ExecResult, error)
	Uninstall(context.Context, *HandlerRequest) (*ExecResult, error)
	FactName(context.Context, *FactNameRequest) (*FactNameResponse, error)
	ScanRole(context.Context, *ScanRoleRequest) (*ScanRoleResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedHandlerPluginServer()
}

// UnimplementedHandlerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandlerPluginServer struct{}

func (UnimplementedHandlerPluginServer) ListHandlers(context.Context, *ListHandlersRequest) (*ListHandlersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHandlers not implemented")
}
func (UnimplementedHandlerPluginServer) Test(context.Context, *HandlerRequest) (*TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedHandlerPluginServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedHandlerPluginServer) Install(context.Context, *HandlerRequest) (*ExecResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedHandlerPluginServer) Uninstall(context.Context, *HandlerRequest) (*ExecResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Uninstall not implemented")
}
func (UnimplementedHandlerPluginServer) FactName(context.Context, *FactNameRequest) (*FactNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactName not implemented")
}
func (UnimplementedHandlerPluginServer) ScanRole(context.Context, *ScanRoleRequest) (*ScanRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanRole not implemented")
}
func (UnimplementedHandlerPluginServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedHandlerPluginServer) mustEmbedUnimplementedHandlerPluginServer() {}
func (UnimplementedHandlerPluginServer) testEmbeddedByValue()                       {}

// UnsafeHandlerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandlerPluginServer will
// result in compilation errors.
type UnsafeHandlerPluginServer interface {
	mustEmbedUnimplementedHandlerPluginServer()
}

func RegisterHandlerPluginServer(s grpc.ServiceRegistrar, srv HandlerPluginServer) {
	// If the following call panics, it indicates UnimplementedHandlerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandlerPlugin_ServiceDesc, srv)
}

func _HandlerPlugin_ListHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).ListHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_ListHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).ListHandlers(ctx, req.(*ListHandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).Test(ctx, req.(*HandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_Install_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).Install(ctx, req.(*HandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_Uninstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).Uninstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_Uninstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).Uninstall(ctx, req.(*HandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_FactName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).FactName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_FactName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).FactName(ctx, req.(*FactNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_ScanRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).ScanRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_ScanRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).ScanRole(ctx, req.(*ScanRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerPlugin_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerPluginServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerPlugin_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerPluginServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandlerPlugin_ServiceDesc is the grpc.ServiceDesc for HandlerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandlerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ironstate.plugin.v1.HandlerPlugin",
	HandlerType: (*HandlerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHandlers",
			Handler:    _HandlerPlugin_ListHandlers_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _HandlerPlugin_Test_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _HandlerPlugin_Describe_Handler,
		},
		{
			MethodName: "Install",
			Handler:    _HandlerPlugin_Install_Handler,
		},
		{
			MethodName: "Uninstall",
			Handler:    _HandlerPlugin_Uninstall_Handler,
		},
		{
			MethodName: "FactName",
			Handler:    _HandlerPlugin_FactName_Handler,
		},
		{
			MethodName: "ScanRole",
			Handler:    _HandlerPlugin_ScanRole_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _HandlerPlugin_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/handler.proto",
}

const (
	HandlerHostCallback_RenderTemplate_FullMethodName    = "/ironstate.plugin.v1.HandlerHostCallback/RenderTemplate"
	HandlerHostCallback_EvaluateCondition_FullMethodName = "/ironstate.plugin.v1.HandlerHostCallback/EvaluateCondition"
)

// HandlerHostCallbackClient is the client API for HandlerHostCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandlerHostCallbackClient interface {
	RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderTemplateResponse, error)
	EvaluateCondition(ctx context.Context, in *EvaluateConditionRequest, opts ...grpc.CallOption) (*EvaluateConditionResponse, error)
}

type handlerHostCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerHostCallbackClient(cc grpc.ClientConnInterface) HandlerHostCallbackClient {
	return &handlerHostCallbackClient{cc}
}

func (c *handlerHostCallbackClient) RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderTemplateResponse)
	err := c.cc.Invoke(ctx, HandlerHostCallback_RenderTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerHostCallbackClient) EvaluateCondition(ctx context.Context, in *EvaluateConditionRequest, opts ...grpc.CallOption) (*EvaluateConditionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateConditionResponse)
	err := c.cc.Invoke(ctx, HandlerHostCallback_EvaluateCondition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandlerHostCallbackServer is the server API for HandlerHostCallback service.
// All implementations must embed UnimplementedHandlerHostCallbackServer
// for forward compatibility.
type HandlerHostCallbackServer interface {
	RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderTemplateResponse, error)
	EvaluateCondition(context.Context, *EvaluateConditionRequest) (*EvaluateConditionResponse, error)
	mustEmbedUnimplementedHandlerHostCallbackServer()
}

// UnimplementedHandlerHostCallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandlerHostCallbackServer struct{}

func (UnimplementedHandlerHostCallbackServer) RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderTemplate not implemented")
}
func (UnimplementedHandlerHostCallbackServer) EvaluateCondition(context.Context, *EvaluateConditionRequest) (*EvaluateConditionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateCondition not implemented")
}
func (UnimplementedHandlerHostCallbackServer) mustEmbedUnimplementedHandlerHostCallbackServer() {}
func (UnimplementedHandlerHostCallbackServer) testEmbeddedByValue()                             {}

// UnsafeHandlerHostCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandlerHostCallbackServer will
// result in compilation errors.
type UnsafeHandlerHostCallbackServer interface {
	mustEmbedUnimplementedHandlerHostCallbackServer()
}

func RegisterHandlerHostCallbackServer(s grpc.ServiceRegistrar, srv HandlerHostCallbackServer) {
	// If the following call panics, it indicates UnimplementedHandlerHostCallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandlerHostCallback_ServiceDesc, srv)
}

func _HandlerHostCallback_RenderTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerHostCallbackServer).RenderTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerHostCallback_RenderTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerHostCallbackServer).RenderTemplate(ctx, req.(*RenderTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandlerHostCallback_EvaluateCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerHostCallbackServer).EvaluateCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandlerHostCallback_EvaluateCondition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerHostCallbackServer).EvaluateCondition(ctx, req.(*EvaluateConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandlerHostCallback_ServiceDesc is the grpc.ServiceDesc for HandlerHostCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandlerHostCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ironstate.plugin.v1.HandlerHostCallback",
	HandlerType: (*HandlerHostCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderTemplate",
			Handler:    _HandlerHostCallback_RenderTemplate_Handler,
		},
		{
			MethodName: "EvaluateCondition",
			Handler:    _HandlerHostCallback_EvaluateCondition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/handler.proto",
}
