// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/handler.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flat          *structpb.Struct       `protobuf:"bytes,1,opt,name=flat,proto3" json:"flat,omitempty"`
	Apply         bool                   `protobuf:"varint,2,opt,name=apply,proto3" json:"apply,omitempty"`
	Become        *Become                `protobuf:"bytes,3,opt,name=become,proto3" json:"become,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_proto_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetFlat() *structpb.Struct {
	if x != nil {
		return x.Flat
	}
	return nil
}

func (x *Context) GetApply() bool {
	if x != nil {
		return x.Apply
	}
	return false
}

func (x *Context) GetBecome() *Become {
	if x != nil {
		return x.Become
	}
	return nil
}

type Become struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Become) Reset() {
	*x = Become{}
	mi := &file_proto_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Become) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Become) ProtoMessage() {}

func (x *Become) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Become.ProtoReflect.Descriptor instead.
func (*Become) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{1}
}

func (x *Become) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Become) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type HandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	Item          *structpb.Struct       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Context       *Context               `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerRequest) Reset() {
	*x = HandlerRequest{}
	mi := &file_proto_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerRequest) ProtoMessage() {}

func (x *HandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerRequest.ProtoReflect.Descriptor instead.
func (*HandlerRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{2}
}

func (x *HandlerRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *HandlerRequest) GetItem() *structpb.Struct {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *HandlerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandlerRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       *HandlerRequest        `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_proto_handler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeRequest) GetHandler() *HandlerRequest {
	if x != nil {
		return x.Handler
	}
	return nil
}

func (x *DescribeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satisfied     bool                   `protobuf:"varint,1,opt,name=satisfied,proto3" json:"satisfied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_proto_handler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{4}
}

func (x *TestResponse) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_proto_handler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ExecResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rc            int32                  `protobuf:"varint,1,opt,name=rc,proto3" json:"rc,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	StdoutLines   []string               `protobuf:"bytes,3,rep,name=stdout_lines,json=stdoutLines,proto3" json:"stdout_lines,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StderrLines   []string               `protobuf:"bytes,5,rep,name=stderr_lines,json=stderrLines,proto3" json:"stderr_lines,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_proto_handler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{6}
}

func (x *ExecResult) GetRc() int32 {
	if x != nil {
		return x.Rc
	}
	return 0
}

func (x *ExecResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResult) GetStdoutLines() []string {
	if x != nil {
		return x.StdoutLines
	}
	return nil
}

func (x *ExecResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResult) GetStderrLines() []string {
	if x != nil {
		return x.StderrLines
	}
	return nil
}

func (x *ExecResult) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type ListHandlersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHandlersRequest) Reset() {
	*x = ListHandlersRequest{}
	mi := &file_proto_handler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHandlersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHandlersRequest) ProtoMessage() {}

func (x *ListHandlersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHandlersRequest.ProtoReflect.Descriptor instead.
func (*ListHandlersRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{7}
}

type ListHandlersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerNames  []string               `protobuf:"bytes,1,rep,name=handler_names,json=handlerNames,proto3" json:"handler_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHandlersResponse) Reset() {
	*x = ListHandlersResponse{}
	mi := &file_proto_handler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHandlersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHandlersResponse) ProtoMessage() {}

func (x *ListHandlersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHandlersResponse.ProtoReflect.Descriptor instead.
func (*ListHandlersResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{8}
}

func (x *ListHandlersResponse) GetHandlerNames() []string {
	if x != nil {
		return x.HandlerNames
	}
	return nil
}

type FactNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	Item          *structpb.Struct       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactNameRequest) Reset() {
	*x = FactNameRequest{}
	mi := &file_proto_handler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactNameRequest) ProtoMessage() {}

func (x *FactNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactNameRequest.ProtoReflect.Descriptor instead.
func (*FactNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{9}
}

func (x *FactNameRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *FactNameRequest) GetItem() *structpb.Struct {
	if x != nil {
		return x.Item
	}
	return nil
}

type FactNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Produced      bool                   `protobuf:"varint,2,opt,name=produced,proto3" json:"produced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactNameResponse) Reset() {
	*x = FactNameResponse{}
	mi := &file_proto_handler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactNameResponse) ProtoMessage() {}

func (x *FactNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactNameResponse.ProtoReflect.Descriptor instead.
func (*FactNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{10}
}

func (x *FactNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactNameResponse) GetProduced() bool {
	if x != nil {
		return x.Produced
	}
	return false
}

type ScanRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRoleRequest) Reset() {
	*x = ScanRoleRequest{}
	mi := &file_proto_handler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRoleRequest) ProtoMessage() {}

func (x *ScanRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRoleRequest.ProtoReflect.Descriptor instead.
func (*ScanRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{11}
}

func (x *ScanRoleRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

type ScanRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Supported     bool                   `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRoleResponse) Reset() {
	*x = ScanRoleResponse{}
	mi := &file_proto_handler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRoleResponse) ProtoMessage() {}

func (x *ScanRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRoleResponse.ProtoReflect.Descriptor instead.
func (*ScanRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{12}
}

func (x *ScanRoleResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ScanRoleResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	Context       *Context               `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_handler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{13}
}

func (x *ScanRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *ScanRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScanItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_handler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{14}
}

func (x *ScanResponse) GetItems() []*ScanItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ScanItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanItem) Reset() {
	*x = ScanItem{}
	mi := &file_proto_handler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanItem) ProtoMessage() {}

func (x *ScanItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanItem.ProtoReflect.Descriptor instead.
func (*ScanItem) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{15}
}

func (x *ScanItem) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ScanItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanItem) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ScanItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RenderTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,2,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderTemplateRequest) Reset() {
	*x = RenderTemplateRequest{}
	mi := &file_proto_handler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderTemplateRequest) ProtoMessage() {}

func (x *RenderTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderTemplateRequest.ProtoReflect.Descriptor instead.
func (*RenderTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{16}
}

func (x *RenderTemplateRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *RenderTemplateRequest) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

type RenderTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rendered      string                 `protobuf:"bytes,1,opt,name=rendered,proto3" json:"rendered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderTemplateResponse) Reset() {
	*x = RenderTemplateResponse{}
	mi := &file_proto_handler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderTemplateResponse) ProtoMessage() {}

func (x *RenderTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderTemplateResponse.ProtoReflect.Descriptor instead.
func (*RenderTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{17}
}

func (x *RenderTemplateResponse) GetRendered() string {
	if x != nil {
		return x.Rendered
	}
	return ""
}

type EvaluateConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,2,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateConditionRequest) Reset() {
	*x = EvaluateConditionRequest{}
	mi := &file_proto_handler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateConditionRequest) ProtoMessage() {}

func (x *EvaluateConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateConditionRequest.ProtoReflect.Descriptor instead.
func (*EvaluateConditionRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{18}
}

func (x *EvaluateConditionRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *EvaluateConditionRequest) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

type EvaluateConditionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateConditionResponse) Reset() {
	*x = EvaluateConditionResponse{}
	mi := &file_proto_handler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateConditionResponse) ProtoMessage() {}

func (x *EvaluateConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateConditionResponse.ProtoReflect.Descriptor instead.
func (*EvaluateConditionResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{19}
}

func (x *EvaluateConditionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_proto_handler_proto protoreflect.FileDescriptor

const file_proto_handler_proto_rawDesc = "" +
	"\n" +
	"\x13proto/handler.proto\x12\x13ironstate.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x81\x01\n" +
	"\aContext\x12+\n" +
	"\x04flat\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04flat\x12\x14\n" +
	"\x05apply\x18\x02 \x01(\bR\x05apply\x123\n" +
	"\x06become\x18\x03 \x01(\v2\x1b.ironstate.plugin.v1.BecomeR\x06become\"6\n" +
	"\x06Become\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"\xac\x01\n" +
	"\x0eHandlerRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x12+\n" +
	"\x04item\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04item\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x126\n" +
	"\acontext\x18\x04 \x01(\v2\x1c.ironstate.plugin.v1.ContextR\acontext\"h\n" +
	"\x0fDescribeRequest\x12=\n" +
	"\ahandler\x18\x01 \x01(\v2#.ironstate.plugin.v1.HandlerRequestR\ahandler\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\",\n" +
	"\fTestResponse\x12\x1c\n" +
	"\tsatisfied\x18\x01 \x01(\bR\tsatisfied\"4\n" +
	"\x10DescribeResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"\xc1\x01\n" +
	"\n" +
	"ExecResult\x12\x0e\n" +
	"\x02rc\x18\x01 \x01(\x05R\x02rc\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12!\n" +
	"\fstdout_lines\x18\x03 \x03(\tR\vstdoutLines\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12!\n" +
	"\fstderr_lines\x18\x05 \x03(\tR\vstderrLines\x12-\n" +
	"\x05extra\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05extra\"\x15\n" +
	"\x13ListHandlersRequest\";\n" +
	"\x14ListHandlersResponse\x12#\n" +
	"\rhandler_names\x18\x01 \x03(\tR\fhandlerNames\"a\n" +
	"\x0fFactNameRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x12+\n" +
	"\x04item\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04item\"B\n" +
	"\x10FactNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bproduced\x18\x02 \x01(\bR\bproduced\"4\n" +
	"\x0fScanRoleRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\"D\n" +
	"\x10ScanRoleResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1c\n" +
	"\tsupported\x18\x02 \x01(\bR\tsupported\"h\n" +
	"\vScanRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x1c.ironstate.plugin.v1.ContextR\acontext\"C\n" +
	"\fScanResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.ironstate.plugin.v1.ScanItemR\x05items\"{\n" +
	"\bScanItem\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"j\n" +
	"\x15RenderTemplateRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x125\n" +
	"\tvariables\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tvariables\"4\n" +
	"\x16RenderTemplateResponse\x12\x1a\n" +
	"\brendered\x18\x01 \x01(\tR\brendered\"q\n" +
	"\x18EvaluateConditionRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x125\n" +
	"\tvariables\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tvariables\"3\n" +
	"\x19EvaluateConditionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result2\xc0\x05\n" +
	"\rHandlerPlugin\x12c\n" +
	"\fListHandlers\x12(.ironstate.plugin.v1.ListHandlersRequest\x1a).ironstate.plugin.v1.ListHandlersResponse\x12N\n" +
	"\x04Test\x12#.ironstate.plugin.v1.HandlerRequest\x1a!.ironstate.plugin.v1.TestResponse\x12W\n" +
	"\bDescribe\x12$.ironstate.plugin.v1.DescribeRequest\x1a%.ironstate.plugin.v1.DescribeResponse\x12O\n" +
	"\aInstall\x12#.ironstate.plugin.v1.HandlerRequest\x1a\x1f.ironstate.plugin.v1.ExecResult\x12Q\n" +
	"\tUninstall\x12#.ironstate.plugin.v1.HandlerRequest\x1a\x1f.ironstate.plugin.v1.ExecResult\x12W\n" +
	"\bFactName\x12$.ironstate.plugin.v1.FactNameRequest\x1a%.ironstate.plugin.v1.FactNameResponse\x12W\n" +
	"\bScanRole\x12$.ironstate.plugin.v1.ScanRoleRequest\x1a%.ironstate.plugin.v1.ScanRoleResponse\x12K\n" +
	"\x04Scan\x12 .ironstate.plugin.v1.ScanRequest\x1a!.ironstate.plugin.v1.ScanResponse2\xf4\x01\n" +
	"\x13HandlerHostCallback\x12i\n" +
	"\x0eRenderTemplate\x12*.ironstate.plugin.v1.RenderTemplateRequest\x1a+.ironstate.plugin.v1.RenderTemplateResponse\x12r\n" +
	"\x11EvaluateCondition\x12-.ironstate.plugin.v1.EvaluateConditionRequest\x1a..ironstate.plugin.v1.EvaluateConditionResponseB5Z3github.com/TacoContent/ironstate/sdk/proto;pluginpbb\x06proto3"

var (
	file_proto_handler_proto_rawDescOnce sync.Once
	file_proto_handler_proto_rawDescData []byte
)

func file_proto_handler_proto_rawDescGZIP() []byte {
	file_proto_handler_proto_rawDescOnce.Do(func() {
		file_proto_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_handler_proto_rawDesc), len(file_proto_handler_proto_rawDesc)))
	})
	return file_proto_handler_proto_rawDescData
}

var file_proto_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_handler_proto_goTypes = []any{
	(*Context)(nil),                   // 0: ironstate.plugin.v1.Context
	(*Become)(nil),                    // 1: ironstate.plugin.v1.Become
	(*HandlerRequest)(nil),            // 2: ironstate.plugin.v1.HandlerRequest
	(*DescribeRequest)(nil),           // 3: ironstate.plugin.v1.DescribeRequest
	(*TestResponse)(nil),              // 4: ironstate.plugin.v1.TestResponse
	(*DescribeResponse)(nil),          // 5: ironstate.plugin.v1.DescribeResponse
	(*ExecResult)(nil),                // 6: ironstate.plugin.v1.ExecResult
	(*ListHandlersRequest)(nil),       // 7: ironstate.plugin.v1.ListHandlersRequest
	(*ListHandlersResponse)(nil),      // 8: ironstate.plugin.v1.ListHandlersResponse
	(*FactNameRequest)(nil),           // 9: ironstate.plugin.v1.FactNameRequest
	(*FactNameResponse)(nil),          // 10: ironstate.plugin.v1.FactNameResponse
	(*ScanRoleRequest)(nil),           // 11: ironstate.plugin.v1.ScanRoleRequest
	(*ScanRoleResponse)(nil),          // 12: ironstate.plugin.v1.ScanRoleResponse
	(*ScanRequest)(nil),               // 13: ironstate.plugin.v1.ScanRequest
	(*ScanResponse)(nil),              // 14: ironstate.plugin.v1.ScanResponse
	(*ScanItem)(nil),                  // 15: ironstate.plugin.v1.ScanItem
	(*RenderTemplateRequest)(nil),     // 16: ironstate.plugin.v1.RenderTemplateRequest
	(*RenderTemplateResponse)(nil),    // 17: ironstate.plugin.v1.RenderTemplateResponse
	(*EvaluateConditionRequest)(nil),  // 18: ironstate.plugin.v1.EvaluateConditionRequest
	(*EvaluateConditionResponse)(nil), // 19: ironstate.plugin.v1.EvaluateConditionResponse
	(*structpb.Struct)(nil),           // 20: google.protobuf.Struct
}
var file_proto_handler_proto_depIdxs = []int32{
	20, // 0: ironstate.plugin.v1.Context.flat:type_name -> google.protobuf.Struct
	1,  // 1: ironstate.plugin.v1.Context.become:type_name -> ironstate.plugin.v1.Become
	20, // 2: ironstate.plugin.v1.HandlerRequest.item:type_name -> google.protobuf.Struct
	0,  // 3: ironstate.plugin.v1.HandlerRequest.context:type_name -> ironstate.plugin.v1.Context
	2,  // 4: ironstate.plugin.v1.DescribeRequest.handler:type_name -> ironstate.plugin.v1.HandlerRequest
	20, // 5: ironstate.plugin.v1.ExecResult.extra:type_name -> google.protobuf.Struct
	20, // 6: ironstate.plugin.v1.FactNameRequest.item:type_name -> google.protobuf.Struct
	0,  // 7: ironstate.plugin.v1.ScanRequest.context:type_name -> ironstate.plugin.v1.Context
	15, // 8: ironstate.plugin.v1.ScanResponse.items:type_name -> ironstate.plugin.v1.ScanItem
	20, // 9: ironstate.plugin.v1.ScanItem.config:type_name -> google.protobuf.Struct
	20, // 10: ironstate.plugin.v1.RenderTemplateRequest.variables:type_name -> google.protobuf.Struct
	20, // 11: ironstate.plugin.v1.EvaluateConditionRequest.variables:type_name -> google.protobuf.Struct
	7,  // 12: ironstate.plugin.v1.HandlerPlugin.ListHandlers:input_type -> ironstate.plugin.v1.ListHandlersRequest
	2,  // 13: ironstate.plugin.v1.HandlerPlugin.Test:input_type -> ironstate.plugin.v1.HandlerRequest
	3,  // 14: ironstate.plugin.v1.HandlerPlugin.Describe:input_type -> ironstate.plugin.v1.DescribeRequest
	2,  // 15: ironstate.plugin.v1.HandlerPlugin.Install:input_type -> ironstate.plugin.v1.HandlerRequest
	2,  // 16: ironstate.plugin.v1.HandlerPlugin.Uninstall:input_type -> ironstate.plugin.v1.HandlerRequest
	9,  // 17: ironstate.plugin.v1.HandlerPlugin.FactName:input_type -> ironstate.plugin.v1.FactNameRequest
	11, // 18: ironstate.plugin.v1.HandlerPlugin.ScanRole:input_type -> ironstate.plugin.v1.ScanRoleRequest
	13, // 19: ironstate.plugin.v1.HandlerPlugin.Scan:input_type -> ironstate.plugin.v1.ScanRequest
	16, // 20: ironstate.plugin.v1.HandlerHostCallback.RenderTemplate:input_type -> ironstate.plugin.v1.RenderTemplateRequest
	18, // 21: ironstate.plugin.v1.HandlerHostCallback.EvaluateCondition:input_type -> ironstate.plugin.v1.EvaluateConditionRequest
	8,  // 22: ironstate.plugin.v1.HandlerPlugin.ListHandlers:output_type -> ironstate.plugin.v1.ListHandlersResponse
	4,  // 23: ironstate.plugin.v1.HandlerPlugin.Test:output_type -> ironstate.plugin.v1.TestResponse
	5,  // 24: ironstate.plugin.v1.HandlerPlugin.Describe:output_type -> ironstate.plugin.v1.DescribeResponse
	6,  // 25: ironstate.plugin.v1.HandlerPlugin.Install:output_type -> ironstate.plugin.v1.ExecResult
	6,  // 26: ironstate.plugin.v1.HandlerPlugin.Uninstall:output_type -> ironstate.plugin.v1.ExecResult
	10, // 27: ironstate.plugin.v1.HandlerPlugin.FactName:output_type -> ironstate.plugin.v1.FactNameResponse
	12, // 28: ironstate.plugin.v1.HandlerPlugin.ScanRole:output_type -> ironstate.plugin.v1.ScanRoleResponse
	14, // 29: ironstate.plugin.v1.HandlerPlugin.Scan:output_type -> ironstate.plugin.v1.ScanResponse
	17, // 30: ironstate.plugin.v1.HandlerHostCallback.RenderTemplate:output_type -> ironstate.plugin.v1.RenderTemplateResponse
	19, // 31: ironstate.plugin.v1.HandlerHostCallback.EvaluateCondition:output_type -> ironstate.plugin.v1.EvaluateConditionResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_handler_proto_init() }
func file_proto_handler_proto_init() {
	if File_proto_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_handler_proto_rawDesc), len(file_proto_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_handler_proto_goTypes,
		DependencyIndexes: file_proto_handler_proto_depIdxs,
		MessageInfos:      file_proto_handler_proto_msgTypes,
	}.Build()
	File_proto_handler_proto = out.File
	file_proto_handler_proto_goTypes = nil
	file_proto_handler_proto_depIdxs = nil
}
