---

tasks:
  - name: Install Python
    tags:
      - languages
      - python
    winget:
      package: "${{ languages.python | toggle(defaults.languages.python) }}"
      state: "${{ languages.python | ternary('present', 'absent') }}"
