---

tasks:
  - name: Install JetBrains Aqua Editor
    when: development.editors | enabled('aqua')
    winget:
      package: JetBrains.Aqua
      state: "${{ development.editors | enabled('aqua') | ternary('present', 'absent') }}"
      source: winget