---

tasks:
  - name: Install JetBrains IntelliJ Editor
    when: development.editors | enabled('intellij')
    winget:
      package: JetBrains.IntelliJIDEA.Community
      state: "${{ development.editors | enabled('intellij') | ternary('present', 'absent') }}"
      source: winget