---

tasks:
  - name: Install Gum
    tags: 
      - tui
      - cli
    xget:
      package: charmbracelet/gum
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("gum") | extension("exe") }}
        - --upgrade-only

  - name: Install JQ
    tags: 
      - json
      - cli
    xget:
      package: jqlang/jq
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("jq") | extension("exe") }}
        - --upgrade-only

  - name: Install YQ
    tags: 
      - yaml
      - cli
      - cli.yq
    xget:
      package: mikefarah/yq
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("yq") | extension("exe") }}
        - --upgrade-only
        - --ignore=".sbom.json"

  - name: Install Bat
    id: install_bat
    tags:
      - cli
      - cli.bat
    xget:
      package: sharkdp/bat
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("bat") | extension("exe") }}
        - --upgrade-only

  - name: Bat Exists
    tags:
      - cli
      - cli.bat
    id: bat_exists
    shell:
      command: Get-Command bat
  
  - name: Disable Cat from CoreUtils
    tags:
      - cli
      - cli.bat
    shell:
      command: |
        & 'coreutils-manager.exe' disable cat
    when:
      - facts.os_family == "windows"
      - install_bat.rc == 0
      - bat_exists.rc == 0

  - name: Install FD
    tags: 
      - cli
    xget:
      package: sharkdp/fd
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("fd") | extension("exe") }}
        - --upgrade-only
        - --asset="-gnu.zip"

  - name: Install Andcli
    tags: 
      - cli
    xget:
      package: tjblackheart/andcli
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("andcli") | extension("exe") }}
        - --upgrade-only

  - name: Install Clipboard
    tags:
      - clipboard
      - cli
    xget:
      package: Slackadays/Clipboard
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("cb") | extension("exe") }}
        - --upgrade-only

  - name: Install Envdiff
    tags: 
      - env
      - cli
    xget:
      package: GBerghoff/envdiff
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("envdiff") | extension("exe") }}
        - --upgrade-only
        - --asset=".zip"

  - name: Install Envfetch
    tags:
      - env
      - cli
    xget:
      package: ankddev/envfetch
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("envfetch") | extension("exe") }}
        - --upgrade-only
        - --asset=".exe"

  - name: Install Envx
    tags: 
      - env
      - cli
    xget:
      package: mikeleppane/envx
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("envx") | extension("exe") }}
        - --upgrade-only

  - name: Install Fx
    tags: 
      - json
      - cli
    xget:
      package: antonmedv/fx
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | join("fx") | extension("exe") }}
        - --upgrade-only

  - name: Install Chezmoi
    tags: 
      - dotfiles
      - cli
    winget:
      package: twpayne.chezmoi
      source: winget
      state: ${{ package.state }}

  - name: Install Task
    tags: 
      - task
      - cli
    winget:
      package: Task.Task
      source: winget
      state: ${{ package.state }}

  - name: Install Croc
    tags:
      - file-transfer
      - cli
    winget:
      package: schollz.croc
      source: winget
      state: ${{ package.state }}

  - name: Install Superfile
    tags: 
      - files
      - cli
    winget:
      package: yorukot.superfile
      source: winget
      state: ${{ package.state }}

  - name: Install Tealdeer
    tags: 
      - docs
      - cli
    cargo:
      package: tealdeer
      state: ${{ package.state }}

  - name: Install Dust
    tags: 
      - cli
    xget:
      package: bootandy/dust
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("dust") | extension("exe") }}
        - --upgrade-only

  - name: Install Fastfetch
    tags:
      - system-info
      - cli
    xget:
      package: fastfetch-cli/fastfetch
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("fastfetch") | extension("exe") }}
        - --upgrade-only
        - --asset=".zip"

  - name: Install Procs
    tags: 
      - process
      - cli
    xget:
      package: dalance/procs/
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("procs") | extension("exe") }}
        - --upgrade-only

  - name: Install Sd
    tags:
      - text
      - cli
    xget:
      package: chmln/sd
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("sd") | extension("exe") }}
        - --upgrade-only

  - name: Install totp-cli
    tags: 
      - security
      - cli
      - totp
    xget:
      package: yitsushi/totp-cli
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("totp") | extension("exe") }}
        - --upgrade-only
        - --asset=".zip"

  - name: Install Hostctl
    tags: 
      - hosts
      - cli
    xget:
      package: guumaster/hostctl
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("hostctl") | extension("exe") }}
        - --upgrade-only
        - --asset="64-bit.zip"

  - tags: 
      - weather
      - cli
    xget:
      package: Tairesh/rustormy
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("rustormy") | extension("exe") }}
        - --upgrade-only
        - --asset=".zip"

  - name: Install NBping
    tags: 
      - network
      - cli
    xget:
      package: hanshuaikang/NBping
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("nbping") | extension("exe") }}
        - --upgrade-only
        - --asset=".zip"