---

tasks:

  - name: GitHub Atom Editor
    tags:
      - development
      - development.editors
      - development.editors.atom
    winget:
      package: GitHub.Atom
      state: "${{ development.editors | enabled('atom') | ternary('present', 'absent') }}"

  - name: GitHub Atom Editor (Beta)
    tags:
      - development
      - development.editors
      - development.editors.atom
    winget:
      package: GitHub.Atom.Beta
      state: "${{ development.editors | enabled('atom_beta') | ternary('present', 'absent') }}"