---

tasks:
  - name: Install JetBrains RubyMine Editor
    when: development.editors | enabled('rubymine')
    winget:
      package: JetBrains.RubyMine
      state: "${{ development.editors | enabled('rubymine') | ternary('present', 'absent') }}"
      source: winget