---

tasks:
  - name: Install JetBrains PhpStorm Editor
    when: development.editors | enabled('phpstorm')
    winget:
      package: JetBrains.PhpStorm
      state: "${{ development.editors | enabled('phpstorm') | ternary('present', 'absent') }}"
      source: winget