---

vars:
  development:
    editors: false
      # vscode: true
      # vscode_insiders: false
      # nano: true # a shim to wsl via powershell function
      # micro: true
      # goland: true
      # aqua: true
      # zettlr: true
      # rider: true
      # resharper: true
      # dataspell: true
      # pycharm: true
      # intellij: true
      # phpstorm: true
      # rubymine: true
      # clion: true
      # datagrip: true
      # webstorm: true
      # rustover: true
      # notepadplusplus: true

tasks:

  - name: Include VSCode Editor Role
    tags:
      - development
      - development.editors
      - development.editors.vscode
      - vscode
    when: development.editors | enabled('vscode')
    include:
      name: roles/development/editors/vscode
      state: ${{ package.state }}

  - name: Include Nano Editor Role
    tags:
      - development
      - development.editors
      - development.editors.nano
      - nano
    when: development.editors | enabled('nano')
    include:
      name: roles/development/editors/nano
      state: ${{ package.state }}

  - name: Include Micro Editor Role
    tags:
      - development
      - development.editors
      - development.editors.micro
      - micro
    when: development.editors | enabled('micro')
    include:
      name: roles/development/editors/micro
      state: ${{ package.state }}

  - name: Include JetBrains Role
    tags:
      - development
      - development.editors
      - jetbrains
    when: development.editors | enabled()
    include:
      name: roles/development/editors/jetbrains
      state: ${{ package.state }}

  - name: Install Notepad++ Editor
    tags:
      - development
      - development.editors
      - notepadplusplus
    when: development.editors | enabled('notepadplusplus')
    winget:
      package: Notepad++.Notepad++
      state: ${{ package.state }}

  - name: Include Zettlr Editor Role
    tags:
      - development
      - development.editors
      - zettlr
    when: development.editors | enabled('zettlr')
    include:
      name: roles/development/editors/zettlr
      state: ${{ package.state }}
