---

vars:
  development:
    editors: false
      # vscode: true
      # vscode_insiders: false
      # nano: true # a shim to wsl via powershell function
      # micro: true
      # goland: true
      # aqua: true
      # zettlr: true
      # rider: true
      # resharper: true
      # dataspell: true
      # pycharm: true
      # intellij: true
      # phpstorm: true
      # rubymine: true
      # clion: true
      # datagrip: true
      # webstorm: true
      # rustover: true
      # notepadplusplus: true
      # android_studio: true

tasks:

  - name: Include VSCode Editor Role
    tags:
      - development
      - development.editors
      - development.editors.vscode
      - vscode
    when: development.editors | enabled('vscode')
    include:
      name: roles/development/editors/vscode

  - name: Include GitHub Atom Editor Role
    tags:
      - development
      - development.editors
      - development.editors.atom
      - atom
    when: development.editors | enabled('atom')
    include:
      name: roles/development/editors/atom

  - name: Include Nano Editor Role
    tags:
      - development
      - development.editors
      - development.editors.nano
      - nano
    include:
      name: roles/development/editors/nano

  - name: Include Micro Editor Role
    tags:
      - development
      - development.editors
      - development.editors.micro
      - micro
    when: development.editors | enabled('micro')
    include:
      name: roles/development/editors/micro

  - name: Include JetBrains Role
    tags:
      - development
      - development.editors
      - development.editors.jetbrains
    when: development.editors | enabled()
    include:
      name: roles/development/editors/jetbrains

  - name: Install Notepad++ Editor
    tags:
      - development
      - development.editors
      - notepadplusplus
    when: development.editors | enabled('notepadplusplus')
    winget:
      package: Notepad++.Notepad++

  - name: Include Zettlr Editor Role
    tags:
      - development
      - development.editors
      - zettlr
    when: development.editors | enabled('zettlr')
    include:
      name: roles/development/editors/zettlr

  - name: Include Android Studio Editor Role
    tags:
      - development
      - development.editors
    when: development.editors | enabled('android_studio')
    include:
      name: roles/development/editors/android-studio
