---

tasks:

  - name: Sysinternals Suite
    when: system.tools | enabled('sysinternals')
    include:
      name: roles/system/tools/sysinternals
    tags:
      - system
      - system.tools
      - system.tools.sysinternals