---

tasks:
  - name: Install JetBrains WebStorm Editor
    when: development.editors | enabled('webstorm')
    winget:
      package: JetBrains.WebStorm
      state: "${{ development.editors | enabled('webstorm') | ternary('present', 'absent') }}"
      source: winget