---

tasks:

  - name: Install JetBrains GoLand Editor
    when: development.editors | enabled('goland')
    winget:
      package: JetBrains.GoLand
      state: "${{ development.editors | enabled('goland') | ternary('present', 'absent') }}"
      source: winget