---

tasks: 

  - name: Install ssh-list
    tags:
      - ssh
    eget:
      package: akinoiro/ssh-list
      state: present
      args:
        - --to=~/.local/bin/ssh-list.exe
        - --upgrade-only
        - --asset=".zip"

  - name: Ensure authorized_keys are set up
    tags:
      - ssh
    include:
      name: roles/ssh/authorized_keys

  - name: Ensure SSH host config is set up
    tags:
      - ssh
    include:
      name: roles/ssh/config
