---
tasks:

  - name: Install Visual Studio Code
    tags:
      - development
      - development.editors
      - development.editors.vscode
    when: development.editors.vscode is defined
    winget:
      package: Microsoft.VisualStudioCode
      state: "${{ development.editors | enabled('vscode') | ternary('present', 'absent') }}"
      source: winget

  - name: Install Visual Studio Code Insiders
    tags:
      - development
      - development.editors
      - development.editors.vscode.insiders
    when: development.editors.vscode_insiders is defined
    winget:
      package: Microsoft.VisualStudioCode.Insiders
      state: "${{ development.editors | enabled('vscode_insiders') | ternary('present', 'absent') }}"
      source: winget
