---

tasks:
  # - name: Install PowerShell
  #   winget:
  #     package: Microsoft.Powershell
  #     source: winget
  #     state: present

  - name: PowerShell System Profile Path Fact
    fact:
      name: pwsh_system_profile_path
      shell:
        command: Write-Output $PROFILE
      value: "${{ stdout | dirname }}"

  - name: PowerShell System Profile Fact
    fact:
      name: pwsh_system_profile
      shell:
        command: Write-Output $PROFILE
    failed_when: rc != 0 or (stdout | length == 0)

  - name: PowerShell User Defined Profile Path Fact
    fact:
      name: pwsh_user_profile_path
      value: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) | dirname }}"

  - name: PowerShell User Defined Profile Fact
    fact:
      name: pwsh_user_profile
      value: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}"

  - name: Register User Profile
    blockinfile:
      create: false
      state: present
      dest: "${{ facts.pwsh_system_profile }}"
      block: |
        $PROFILE_PATH = "${{ facts.pwsh_user_profile }}"
        if (Test-Path $PROFILE_PATH) {
            . $PROFILE_PATH
        }

  - name: Import PowerShell Modules
    blockinfile:
      create: true
      state: present
      dest: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}"
      block: |
        $env:VIRTUAL_ENV_DISABLE_PROMPT = 1;
        
        $modules = @("posh-git", "Terminal-Icons");
        $modules | ForEach-Object {
          if ( !(Get-Module -ListAvailable -Name "$_") ) {
            Install-Module $_ -Scope CurrentUser -Force;
          }
        };

        $modules | ForEach-Object {
          Import-Module -Name $_;
        }
  - name: Configure PowerShell Host Colors
    blockinfile:
      create: true
      state: present
      dest: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}"
      block: |

        $host.privatedata.ErrorForegroundColor = 'Magenta';
        $host.privatedata.ErrorBackgroundColor = 'Black';
        $host.privatedata.WarningForegroundColor = 'Yellow';
        $host.privatedata.WarningBackgroundColor = 'Black';
        $host.privatedata.DebugForegroundColor = 'DarkGray';
        $host.privatedata.DebugBackgroundColor = 'Black';
        $host.privatedata.VerboseForegroundColor = 'White';
        $host.privatedata.VerboseBackgroundColor = 'Black';
        $host.privatedata.ProgressForegroundColor = 'DarkBlue';
        $host.privatedata.ProgressBackgroundColor = 'DarkCyan';

  - name: Import Chocolatey Profile
    blockinfile:
      create: true
      state: present
      dest: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}"
      block: |
        # Import the Chocolatey Profile that contains the necessary code to enable
        # tab-completions to function for `choco`.
        # Be aware that if you are missing these lines from your profile, tab completion
        # for `choco` will not function.
        # See https://ch0.co/tab-completion for details.
        $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        if (Test-Path($ChocolateyProfile)) {
          Import-Module "$ChocolateyProfile"
        }

  - name: Load Custom PowerShell Source Files
    blockinfile:
      create: false
      state: present
      dest: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}"
      block: |
        # Load custom shell extensions from ${{ facts.pwsh_user_profile_path }}/custom/<category>/*.ps1
        foreach ($category in @("aliases", "exports", "functions", "sources")) {
            $customDir = Join-Path "${{ facts.pwsh_user_profile_path }}" "custom/$category"
            if (Test-Path $customDir) {
                Get-ChildItem -Path $customDir -Filter *.ps1 -File | ForEach-Object {
                    . $_.FullName
                }
            }
        }

  - name: Install Oh-My-Posh
    winget:
      package: JanDeDobbeleer.OhMyPosh
      source: winget
      state: present

  - name: Set up Oh-My-Posh Bin Path
    path:
      paths:
        - ~\AppData\Local\Programs\oh-my-posh\bin
      state: present

  - name: Copy Oh-My-Posh Configuration
    copy:
      src: "files/home/.config/powershell/default.omp.json"
      dest: "${{ shell.pwsh.omp.profile | default(defaults.shell.pwsh.omp.profile) }}"
      state: present

  # - name: Ensure Custom PowerShell Directory Exists
  #   file:
  #     path: "${{ facts.pwsh_user_profile_path }}/custom2"
  #     type: directory
  #     state: present

  - name: Copy Custom PowerShell Files
    copy:
      src: "files/home/.config/powershell/custom/"
      dest: "${{ facts.pwsh_user_profile_path }}/custom/"
      state: present

  - name: Oh-My-Posh Profile
    blockinfile:
      # Do not create the profile file if it does not exist. Fail the task instead.
      create: false
      state: present
      dest: "${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}"
      block: |
        if (Get-Command oh-my-posh -ErrorAction SilentlyContinue) {
            oh-my-posh init pwsh --config "${{ shell.pwsh.omp.profile | default(defaults.shell.pwsh.omp.profile) }}" | Invoke-Expression
        }
