---

tasks:
  - name: Check Rust Installation
    id: rustc
    shell:
      command: Get-Command rustc
  - name: Check Cargo Installation
    id: cargo
    shell:
      command: Get-Command cargo

  - name: Install Rust
    winget:
      package: Rustlang.Rustup
      state: present
    when: rustc.rc != 0 or cargo.rc != 0

  - name: register cargo bin paths
    path:
      paths:
        - ~/.cargo/bin
      state: present

  - name: PowerShell Cargo Environment
    blockinfile:
      create: false
      dest: ${{ shell.pwsh.profile | default(defaults.shell.pwsh.profile) }}
      block: |
        if (Test-Path "$HOME/.cargo/env.ps1") {
          . "$HOME/.cargo/env.ps1"
        }