---

tasks:
  - name: Install JetBrains Rider
    when: development.editors | enabled('rider')
    winget:
      package: JetBrains.Rider
      state: "${{ development.editors | enabled('rider') | ternary('present', 'absent') }}"
      source: winget