---

tasks:

  - name: Install Pass CLI
    tags: 
      - security
      - security.pass-cli
    eget:
      package: reyamira/pass-cli
      state: ${{ security | enabled('pass_cli') | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('pass-cli.exe') }}
        - --upgrade-only
        - --asset=".tar.gz"

  - name: Install COTP
    tags:
      - security
      - security.cotp
    eget:
      package: replydev/cotp
      state: ${{ security | enabled('cotp') | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('cotp.exe') }}
        - --upgrade-only

  - name: Install GAuth
    tags: 
      - security
      - security.gauth
    eget:
      package: pcarrier/gauth
      state: ${{ security | enabled('gauth') | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('gauth.exe') }}
        - --upgrade-only

  - name: Install pwdgen
    tags: 
      - security
      - security.pwdgen
    pipx:
      package: pwdgen
      state: ${{ security | enabled('pwdgen') | ternary('present', 'absent') }}

  - name: Install Age
    tags: 
      - security
      - security.age
    winget:
      package: FiloSottile.age
      source: winget
      state: ${{ security | enabled('age') | ternary('present', 'absent') }}

  - name: Install Syft
    tags: 
      - security
      - security.syft
    eget:
      package: anchore/syft
      state: ${{ security | enabled('syft') | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('syft.exe') }}
        - --upgrade-only
        - --asset=".zip"

  - name: Install Grype
    tags: 
      - security
      - security.grype
    eget:
      package: anchore/grype
      state: ${{ security | enabled('grype') | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('grype.exe') }}
        - --upgrade-only
        - --asset=".zip"
