---

tasks:

  - name: Install Pass CLI
    tags: 
      - security
      - cli
      - password-store
    eget:
      package: reyamira/pass-cli
      state: present
      args:
        - --to=~/.local/bin/pass-cli.exe
        - --upgrade-only
        - --asset=".tar.gz"

  - name: Install COTP
    tags:
      - security
      - cli
      - totp
    eget:
      package: replydev/cotp
      state: ${{ package.state }}
      args:
        - --to=~/.local/bin/cotp.exe
        - --upgrade-only

  - name: Install GAuth
    tags: 
      - security
      - cli
      - totp
    eget:
      package: pcarrier/gauth
      state: present
      args:
        - --to=~/.local/bin/gauth.exe
        - --upgrade-only

  - name: Install pwdgen
    tags: 
      - security
      - cli
    pipx:
      package: pwdgen
      state: present

  - name: Install Age
    tags: 
      - security
      - cli
    winget:
      package: FiloSottile.age
      source: winget
      state: ${{ package.state }}

  - name: Install Syft
    tags: 
      - security
      - sbom
    eget:
      package: anchore/syft
      state: absent
      args:
        - --to=~/.local/bin/syft.exe
        - --upgrade-only
        - --asset=".zip"

  - name: Install Grype
    tags: 
      - security
      - vulnerability-scanning
    eget:
      package: anchore/grype
      state: absent
      args:
        - --to=~/.local/bin/grype.exe
        - --upgrade-only
        - --asset=".zip"
