---

vars:
  development:
    tools:
      jetbrains_toolbox: false

tasks:

  

  - name: Install orhun/git-cliff
    tags:
      - development
      - git
      - changelog
    eget:
      package: orhun/git-cliff
      state: present
      args:
        - --to=~/.local/bin/git-cliff.exe
        - --upgrade-only

  - name: Install caarlos0/svu
    tags:
      - development
      - git
      - versioning
    eget:
      package: caarlos0/svu
      state: present
      args:
        - --to=~/.local/bin/svu.exe
        - --upgrade-only
        - --asset=".zip"

  - name: Install koalaman/shellcheck
    tags: 
      - development
      - development.tools.shellcheck
    eget:
      package: koalaman/shellcheck
      state: present
      args:
        - --to=~/.local/bin/shellcheck.exe
        - --upgrade-only
        - --asset=".zip"

  - name: Install JetBrains Toolbox
    when: development.tools.jetbrains_toolbox | default(false)
    winget:
      package: JetBrains.Toolbox
      state: "${{ package.state | default('present')}}"
      source: winget