package handlers

func (advFirewallHandler) Emoji() string   { return "🧱" }
func (apkHandler) Emoji() string           { return "📦" }
func (aptHandler) Emoji() string           { return "📦" }
func (assertHandler) Emoji() string        { return "✅" }
func (asyncHandler) Emoji() string         { return "⚡" }
func (blockInFileHandler) Emoji() string   { return "🧩" }
func (cargoHandler) Emoji() string         { return "🦀" }
func (chocolateyHandler) Emoji() string    { return "🍫" }
func (copyHandler) Emoji() string          { return "📋" }
func (cronFileHandler) Emoji() string      { return "⏰" }
func (cronHandler) Emoji() string          { return "⏰" }
func (cronUnixHandler) Emoji() string      { return "⏰" }
func (egetHandler) Emoji() string          { return "📦" }
func (factHandler) Emoji() string          { return "🔎" }
func (failHandler) Emoji() string          { return "❌" }
func (fileHandler) Emoji() string          { return "📄" }
func (firewallHandler) Emoji() string      { return "🧱" }
func (flatpakHandler) Emoji() string       { return "📦" }
func (gitHandler) Emoji() string           { return "🌿" }
func (goHandler) Emoji() string            { return "🐹" }
func (groupHandler) Emoji() string         { return "👥" }
func (homebrewHandler) Emoji() string      { return "🍺" }
func (iptablesHandler) Emoji() string      { return "🧱" }
func (lineInFileHandler) Emoji() string    { return "📏" }
func (logHandler) Emoji() string           { return "📢" }
func (macportsHandler) Emoji() string      { return "📦" }
func (mountFactsHandler) Emoji() string    { return "🔎" }
func (npmHandler) Emoji() string           { return "📦" }
func (pacmanHandler) Emoji() string        { return "📦" }
func (pathHandler) Emoji() string          { return "📁" }
func (pipxHandler) Emoji() string          { return "🐍" }
func (registryHandler) Emoji() string      { return "🗃️" }
func (rubyGemHandler) Emoji() string       { return "💎" }
func (scheduledTaskHandler) Emoji() string { return "⏰" }
func (scoopHandler) Emoji() string         { return "📦" }
func (serviceHandler) Emoji() string       { return "🏷️" }
func (shellHandler) Emoji() string         { return "💻" }
func (snapHandler) Emoji() string          { return "📦" }
func (sshHostBlockHandler) Emoji() string  { return "🔐" }
func (symlinksHandler) Emoji() string      { return "🔗" }
func (templateHandler) Emoji() string      { return "📝" }
func (ufwHandler) Emoji() string           { return "🧱" }
func (userHandler) Emoji() string          { return "👤" }
func (waitForHandler) Emoji() string       { return "⏳" }
func (wingetHandler) Emoji() string        { return "📦" }
func (xgetHandler) Emoji() string          { return "📦" }
func (yumHandler) Emoji() string           { return "📦" }
func (zipHandler) Emoji() string           { return "🗜️" }
