---

tasks:
  - name: Install JetBrains Toolbox
    when: development.tools.jetbrains_toolbox is defined
    winget:
      package: JetBrains.Toolbox
      state: "${{ development.tools | enabled('jetbrains_toolbox') | ternary('present', 'absent') }}"
      source: winget