---
tasks:
  - name: Install Micro
    when: (development.editors is mapping or (development.editors | bool)) and (development.editors.micro | default(false))
    winget:
      package: zyedidia.micro
      state: "${{ package.state | default('present')}}"
      source: winget
